/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_safaflissespacefoyer (void)
{
  GtkWidget *safaflissespacefoyer;
  GtkWidget *alignment1;
  GtkWidget *fixed3;
  GtkWidget *FSentry1chercher;
  GtkWidget *FSlabel10bien;
  GtkWidget *vseparator1;
  GtkWidget *FSlabel7msgfoyer;
  GtkWidget *FSlabel61liste;
  GtkWidget *FSbutton1modifierfoyer;
  GtkWidget *alignment11;
  GtkWidget *hbox10;
  GtkWidget *image12;
  GtkWidget *label34;
  GtkWidget *FSimage14recherche;
  GtkWidget *FSbutton2afficherfoyer;
  GtkWidget *alignment13;
  GtkWidget *hbox12;
  GtkWidget *image14;
  GtkWidget *label38;
  GtkWidget *FSbutton2statistique;
  GtkWidget *FSbutton3supprimerfoyer;
  GtkWidget *alignment12;
  GtkWidget *hbox11;
  GtkWidget *image13;
  GtkWidget *label35;
  GtkWidget *flisssafabutton1ajouter;
  GtkWidget *alignment4;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *scrolledwindow1;
  GtkWidget *FStreeview1liste;
  GtkWidget *flisssafabutton2chercher;
  GtkWidget *alignment5;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *FSbutton1actualiser;
  GtkWidget *alignment10;
  GtkWidget *hbox9;
  GtkWidget *image11;
  GtkWidget *label33;

  safaflissespacefoyer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (safaflissespacefoyer), _("Espace Foyer"));

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (safaflissespacefoyer), alignment1);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (alignment1), fixed3);

  FSentry1chercher = gtk_entry_new ();
  gtk_widget_show (FSentry1chercher);
  gtk_fixed_put (GTK_FIXED (fixed3), FSentry1chercher, 552, 176);
  gtk_widget_set_size_request (FSentry1chercher, 88, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry1chercher), 8226);

  FSlabel10bien = gtk_label_new (_("<span color=\"#006080\" font_desc='Tahoma 12'><b>Bienvenue dans l'espace Foyer</b></span>"));
  gtk_widget_show (FSlabel10bien);
  gtk_fixed_put (GTK_FIXED (fixed3), FSlabel10bien, 240, 24);
  gtk_widget_set_size_request (FSlabel10bien, 320, 56);
  gtk_label_set_use_markup (GTK_LABEL (FSlabel10bien), TRUE);
  gtk_misc_set_alignment (GTK_MISC (FSlabel10bien), 0.44, 0.5);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed3), vseparator1, 440, 120);
  gtk_widget_set_size_request (vseparator1, 56, 328);

  FSlabel7msgfoyer = gtk_label_new ("");
  gtk_widget_show (FSlabel7msgfoyer);
  gtk_fixed_put (GTK_FIXED (fixed3), FSlabel7msgfoyer, 488, 352);
  gtk_widget_set_size_request (FSlabel7msgfoyer, 256, 40);

  FSlabel61liste = gtk_label_new (_("Liste des \303\251tudiants H\303\251berg\303\251s"));
  gtk_widget_show (FSlabel61liste);
  gtk_fixed_put (GTK_FIXED (fixed3), FSlabel61liste, 80, 80);
  gtk_widget_set_size_request (FSlabel61liste, 280, 48);
  gtk_misc_set_alignment (GTK_MISC (FSlabel61liste), 0.44, 0.5);

  FSbutton1modifierfoyer = gtk_button_new ();
  gtk_widget_show (FSbutton1modifierfoyer);
  gtk_fixed_put (GTK_FIXED (fixed3), FSbutton1modifierfoyer, 256, 440);
  gtk_widget_set_size_request (FSbutton1modifierfoyer, 88, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (FSbutton1modifierfoyer), alignment11);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox10);

  image12 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox10), image12, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox10), label34, FALSE, FALSE, 0);

  FSimage14recherche = create_pixmap (safaflissespacefoyer, "111 (1).png");
  gtk_widget_show (FSimage14recherche);
  gtk_fixed_put (GTK_FIXED (fixed3), FSimage14recherche, 480, 104);
  gtk_widget_set_size_request (FSimage14recherche, 248, 240);

  FSbutton2afficherfoyer = gtk_button_new ();
  gtk_widget_show (FSbutton2afficherfoyer);
  gtk_fixed_put (GTK_FIXED (fixed3), FSbutton2afficherfoyer, 128, 440);
  gtk_widget_set_size_request (FSbutton2afficherfoyer, 88, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (FSbutton2afficherfoyer), alignment13);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox12);

  image14 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox12), image14, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox12), label38, FALSE, FALSE, 0);

  FSbutton2statistique = gtk_button_new_with_mnemonic (_("Statistique"));
  gtk_widget_show (FSbutton2statistique);
  gtk_fixed_put (GTK_FIXED (fixed3), FSbutton2statistique, 552, 408);
  gtk_widget_set_size_request (FSbutton2statistique, 152, 37);

  FSbutton3supprimerfoyer = gtk_button_new ();
  gtk_widget_show (FSbutton3supprimerfoyer);
  gtk_fixed_put (GTK_FIXED (fixed3), FSbutton3supprimerfoyer, 360, 440);
  gtk_widget_set_size_request (FSbutton3supprimerfoyer, 96, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (FSbutton3supprimerfoyer), alignment12);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox11);

  image13 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox11), image13, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox11), label35, FALSE, FALSE, 0);

  flisssafabutton1ajouter = gtk_button_new ();
  gtk_widget_show (flisssafabutton1ajouter);
  gtk_fixed_put (GTK_FIXED (fixed3), flisssafabutton1ajouter, 24, 440);
  gtk_widget_set_size_request (flisssafabutton1ajouter, 88, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (flisssafabutton1ajouter), alignment4);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed3), scrolledwindow1, 24, 152);
  gtk_widget_set_size_request (scrolledwindow1, 432, 264);

  FStreeview1liste = gtk_tree_view_new ();
  gtk_widget_show (FStreeview1liste);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), FStreeview1liste);
  gtk_widget_set_size_request (FStreeview1liste, 432, 288);

  flisssafabutton2chercher = gtk_button_new ();
  gtk_widget_show (flisssafabutton2chercher);
  gtk_fixed_put (GTK_FIXED (fixed3), flisssafabutton2chercher, 664, 176);
  gtk_widget_set_size_request (flisssafabutton2chercher, 98, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (flisssafabutton2chercher), alignment5);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("chercher"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  FSbutton1actualiser = gtk_button_new ();
  gtk_widget_show (FSbutton1actualiser);
  gtk_fixed_put (GTK_FIXED (fixed3), FSbutton1actualiser, 360, 104);
  gtk_widget_set_size_request (FSbutton1actualiser, 96, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (FSbutton1actualiser), alignment10);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox9);

  image11 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox9), image11, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox9), label33, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) FSentry1chercher, "changed",
                    G_CALLBACK (on_FSentry1chercher_changed),
                    NULL);
  g_signal_connect ((gpointer) FSbutton1modifierfoyer, "clicked",
                    G_CALLBACK (on_FSbutton1modifierfoyer_clicked),
                    NULL);
  g_signal_connect ((gpointer) FSbutton2afficherfoyer, "clicked",
                    G_CALLBACK (on_FSbutton2afficherfoyer_clicked),
                    NULL);
  g_signal_connect ((gpointer) FSbutton2statistique, "clicked",
                    G_CALLBACK (on_flisssafabutton2statistique_clicked),
                    NULL);
  g_signal_connect ((gpointer) FSbutton3supprimerfoyer, "clicked",
                    G_CALLBACK (on_FSbutton3supprimerfoyer_clicked),
                    NULL);
  g_signal_connect ((gpointer) flisssafabutton1ajouter, "clicked",
                    G_CALLBACK (on_flisssafabutton1ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) FStreeview1liste, "row_activated",
                    G_CALLBACK (on_FStreeview1liste_row_activated),
                    NULL);
  g_signal_connect ((gpointer) FStreeview1liste, "focus_in_event",
                    G_CALLBACK (on_FStreeview1liste_focus_in_event),
                    NULL);
  g_signal_connect ((gpointer) flisssafabutton2chercher, "clicked",
                    G_CALLBACK (on_flisssafabutton2chercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) FSbutton1actualiser, "clicked",
                    G_CALLBACK (on_FSbutton1actualiser_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (safaflissespacefoyer, safaflissespacefoyer, "safaflissespacefoyer");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, FSentry1chercher, "FSentry1chercher");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, FSlabel10bien, "FSlabel10bien");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, FSlabel7msgfoyer, "FSlabel7msgfoyer");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, FSlabel61liste, "FSlabel61liste");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, FSbutton1modifierfoyer, "FSbutton1modifierfoyer");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, image12, "image12");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, label34, "label34");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, FSimage14recherche, "FSimage14recherche");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, FSbutton2afficherfoyer, "FSbutton2afficherfoyer");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, image14, "image14");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, label38, "label38");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, FSbutton2statistique, "FSbutton2statistique");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, FSbutton3supprimerfoyer, "FSbutton3supprimerfoyer");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, image13, "image13");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, label35, "label35");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, flisssafabutton1ajouter, "flisssafabutton1ajouter");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, image3, "image3");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, label3, "label3");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, FStreeview1liste, "FStreeview1liste");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, flisssafabutton2chercher, "flisssafabutton2chercher");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, image4, "image4");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, label4, "label4");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, FSbutton1actualiser, "FSbutton1actualiser");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, image11, "image11");
  GLADE_HOOKUP_OBJECT (safaflissespacefoyer, label33, "label33");

  return safaflissespacefoyer;
}

GtkWidget*
create_safaflissAjout (void)
{
  GtkWidget *safaflissAjout;
  GtkWidget *fixed4;
  GtkWidget *FSentry2nom;
  GtkWidget *FSentry3prenom;
  GtkWidget *FSentry4cin;
  GtkObject *FSspinbutton1jour_adj;
  GtkWidget *FSspinbutton1jour;
  GtkObject *FSspinbutton2mois_adj;
  GtkWidget *FSspinbutton2mois;
  GtkObject *FSspinbutton3ans_adj;
  GtkWidget *FSspinbutton3ans;
  GtkWidget *FSentry5ville;
  GtkWidget *FSentry6tel;
  GtkWidget *FSentry7contact;
  GtkWidget *FSentry8nchambre;
  GtkWidget *FSentry9sante;
  GtkWidget *FSlabel9nom;
  GtkWidget *FSlabel10prenom;
  GtkWidget *FSlabel11cin;
  GtkWidget *FSlabel12dn;
  GtkWidget *FSlabel16ville;
  GtkWidget *FSlabel17tel;
  GtkWidget *FSlabel18contact;
  GtkWidget *FSlabel21sante;
  GtkWidget *FSlabel15niveau;
  GtkWidget *FSlabel22payer;
  GtkWidget *FSlabel20nchambre;
  GtkWidget *FSlabel19chambre;
  GtkWidget *FSradiobutton2homme;
  GSList *FSradiobutton2homme_group = NULL;
  GtkWidget *FSradiobutton1femme;
  GtkWidget *FSlabel1idajout;
  GtkWidget *FSentry1idajout;
  GtkWidget *FScheckbutton1condition;
  GtkWidget *FSbutton3ajouter;
  GtkWidget *alignment3;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *FScombobox3niveau;
  GtkWidget *FScombobox2payer;
  GtkWidget *FSlabel41champ2;
  GtkWidget *FSlabel42champ3;
  GtkWidget *FSlabel43champ4;
  GtkWidget *FSlabel44champ5;
  GtkWidget *FSlabel45champ6;
  GtkWidget *FSlabel47champ8;
  GtkWidget *FSlabel48champ9;
  GtkWidget *FSlabel46champ7;
  GtkWidget *FSlabel50champ11;
  GtkWidget *FSlabel49champ10;
  GtkWidget *FSlabel51champchambre;
  GtkWidget *FSlabel1msgajout;
  GtkWidget *FSlabel40champ1;
  GtkWidget *FScombobox1chambreajout;

  safaflissAjout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (safaflissAjout), _("SF_Ajout"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (safaflissAjout), fixed4);

  FSentry2nom = gtk_entry_new ();
  gtk_widget_show (FSentry2nom);
  gtk_fixed_put (GTK_FIXED (fixed4), FSentry2nom, 232, 64);
  gtk_widget_set_size_request (FSentry2nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry2nom), 8226);

  FSentry3prenom = gtk_entry_new ();
  gtk_widget_show (FSentry3prenom);
  gtk_fixed_put (GTK_FIXED (fixed4), FSentry3prenom, 232, 104);
  gtk_widget_set_size_request (FSentry3prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry3prenom), 8226);

  FSentry4cin = gtk_entry_new ();
  gtk_widget_show (FSentry4cin);
  gtk_fixed_put (GTK_FIXED (fixed4), FSentry4cin, 232, 144);
  gtk_widget_set_size_request (FSentry4cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry4cin), 8226);

  FSspinbutton1jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  FSspinbutton1jour = gtk_spin_button_new (GTK_ADJUSTMENT (FSspinbutton1jour_adj), 1, 0);
  gtk_widget_show (FSspinbutton1jour);
  gtk_fixed_put (GTK_FIXED (fixed4), FSspinbutton1jour, 240, 184);
  gtk_widget_set_size_request (FSspinbutton1jour, 56, 24);

  FSspinbutton2mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  FSspinbutton2mois = gtk_spin_button_new (GTK_ADJUSTMENT (FSspinbutton2mois_adj), 1, 0);
  gtk_widget_show (FSspinbutton2mois);
  gtk_fixed_put (GTK_FIXED (fixed4), FSspinbutton2mois, 328, 184);
  gtk_widget_set_size_request (FSspinbutton2mois, 56, 24);

  FSspinbutton3ans_adj = gtk_adjustment_new (1990, 1990, 2021, 1, 10, 10);
  FSspinbutton3ans = gtk_spin_button_new (GTK_ADJUSTMENT (FSspinbutton3ans_adj), 1, 0);
  gtk_widget_show (FSspinbutton3ans);
  gtk_fixed_put (GTK_FIXED (fixed4), FSspinbutton3ans, 424, 184);
  gtk_widget_set_size_request (FSspinbutton3ans, 64, 24);

  FSentry5ville = gtk_entry_new ();
  gtk_widget_show (FSentry5ville);
  gtk_fixed_put (GTK_FIXED (fixed4), FSentry5ville, 232, 256);
  gtk_widget_set_size_request (FSentry5ville, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry5ville), 8226);

  FSentry6tel = gtk_entry_new ();
  gtk_widget_show (FSentry6tel);
  gtk_fixed_put (GTK_FIXED (fixed4), FSentry6tel, 232, 296);
  gtk_widget_set_size_request (FSentry6tel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry6tel), 8226);

  FSentry7contact = gtk_entry_new ();
  gtk_widget_show (FSentry7contact);
  gtk_fixed_put (GTK_FIXED (fixed4), FSentry7contact, 232, 336);
  gtk_widget_set_size_request (FSentry7contact, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry7contact), 8226);

  FSentry8nchambre = gtk_entry_new ();
  gtk_widget_show (FSentry8nchambre);
  gtk_fixed_put (GTK_FIXED (fixed4), FSentry8nchambre, 232, 536);
  gtk_widget_set_size_request (FSentry8nchambre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry8nchambre), 8226);

  FSentry9sante = gtk_entry_new ();
  gtk_widget_show (FSentry9sante);
  gtk_fixed_put (GTK_FIXED (fixed4), FSentry9sante, 232, 376);
  gtk_widget_set_size_request (FSentry9sante, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry9sante), 8226);

  FSlabel9nom = gtk_label_new (_("Nom"));
  gtk_widget_show (FSlabel9nom);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel9nom, 80, 64);
  gtk_widget_set_size_request (FSlabel9nom, 96, 32);

  FSlabel10prenom = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (FSlabel10prenom);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel10prenom, 80, 104);
  gtk_widget_set_size_request (FSlabel10prenom, 96, 32);

  FSlabel11cin = gtk_label_new (_("CIN"));
  gtk_widget_show (FSlabel11cin);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel11cin, 96, 144);
  gtk_widget_set_size_request (FSlabel11cin, 72, 32);

  FSlabel12dn = gtk_label_new (_("Date de Naissance"));
  gtk_widget_show (FSlabel12dn);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel12dn, 72, 176);
  gtk_widget_set_size_request (FSlabel12dn, 144, 40);

  FSlabel16ville = gtk_label_new (_("Ville d'Origine"));
  gtk_widget_show (FSlabel16ville);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel16ville, 80, 256);
  gtk_widget_set_size_request (FSlabel16ville, 120, 32);

  FSlabel17tel = gtk_label_new (_("N\302\260de T\303\251l\303\251phone"));
  gtk_widget_show (FSlabel17tel);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel17tel, 80, 296);
  gtk_widget_set_size_request (FSlabel17tel, 128, 32);

  FSlabel18contact = gtk_label_new (_("Contact Parents"));
  gtk_widget_show (FSlabel18contact);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel18contact, 72, 336);
  gtk_widget_set_size_request (FSlabel18contact, 152, 32);

  FSlabel21sante = gtk_label_new (_("Condition Sanitaire"));
  gtk_widget_show (FSlabel21sante);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel21sante, 80, 376);
  gtk_widget_set_size_request (FSlabel21sante, 160, 32);

  FSlabel15niveau = gtk_label_new (_("Niveau"));
  gtk_widget_show (FSlabel15niveau);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel15niveau, 88, 416);
  gtk_widget_set_size_request (FSlabel15niveau, 88, 24);

  FSlabel22payer = gtk_label_new (_("Payement"));
  gtk_widget_show (FSlabel22payer);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel22payer, 80, 448);
  gtk_widget_set_size_request (FSlabel22payer, 120, 40);

  FSlabel20nchambre = gtk_label_new (_("N\302\260Chambre"));
  gtk_widget_show (FSlabel20nchambre);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel20nchambre, 88, 536);
  gtk_widget_set_size_request (FSlabel20nchambre, 112, 24);

  FSlabel19chambre = gtk_label_new (_("Chambre"));
  gtk_widget_show (FSlabel19chambre);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel19chambre, 96, 496);
  gtk_widget_set_size_request (FSlabel19chambre, 80, 24);

  FSradiobutton2homme = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (FSradiobutton2homme);
  gtk_fixed_put (GTK_FIXED (fixed4), FSradiobutton2homme, 408, 224);
  gtk_widget_set_size_request (FSradiobutton2homme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (FSradiobutton2homme), FSradiobutton2homme_group);
  FSradiobutton2homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (FSradiobutton2homme));

  FSradiobutton1femme = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (FSradiobutton1femme);
  gtk_fixed_put (GTK_FIXED (fixed4), FSradiobutton1femme, 240, 224);
  gtk_widget_set_size_request (FSradiobutton1femme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (FSradiobutton1femme), FSradiobutton2homme_group);
  FSradiobutton2homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (FSradiobutton1femme));

  FSlabel1idajout = gtk_label_new (_("Identifiant"));
  gtk_widget_show (FSlabel1idajout);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel1idajout, 80, 24);
  gtk_widget_set_size_request (FSlabel1idajout, 96, 32);

  FSentry1idajout = gtk_entry_new ();
  gtk_widget_show (FSentry1idajout);
  gtk_fixed_put (GTK_FIXED (fixed4), FSentry1idajout, 232, 24);
  gtk_widget_set_size_request (FSentry1idajout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry1idajout), 8226);

  FScheckbutton1condition = gtk_check_button_new_with_mnemonic (_("Les donn\303\251es sont bien v\303\251rifi\303\251es"));
  gtk_widget_show (FScheckbutton1condition);
  gtk_fixed_put (GTK_FIXED (fixed4), FScheckbutton1condition, 96, 584);
  gtk_widget_set_size_request (FScheckbutton1condition, 312, 24);

  FSbutton3ajouter = gtk_button_new ();
  gtk_widget_show (FSbutton3ajouter);
  gtk_fixed_put (GTK_FIXED (fixed4), FSbutton3ajouter, 416, 568);
  gtk_widget_set_size_request (FSbutton3ajouter, 120, 48);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (FSbutton3ajouter), alignment3);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  FScombobox3niveau = gtk_combo_box_new_text ();
  gtk_widget_show (FScombobox3niveau);
  gtk_fixed_put (GTK_FIXED (fixed4), FScombobox3niveau, 231, 413);
  gtk_widget_set_size_request (FScombobox3niveau, 150, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox3niveau), _("1ere"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox3niveau), _("2eme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox3niveau), _("3eme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox3niveau), _("4eme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox3niveau), _("5eme"));

  FScombobox2payer = gtk_combo_box_new_text ();
  gtk_widget_show (FScombobox2payer);
  gtk_fixed_put (GTK_FIXED (fixed4), FScombobox2payer, 231, 453);
  gtk_widget_set_size_request (FScombobox2payer, 150, 30);
  gtk_container_set_border_width (GTK_CONTAINER (FScombobox2payer), 33);
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox2payer), _("par*tranche"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox2payer), _("par*mois"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox2payer), _("par*annee"));

  FSlabel41champ2 = gtk_label_new ("");
  gtk_widget_show (FSlabel41champ2);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel41champ2, 432, 64);
  gtk_widget_set_size_request (FSlabel41champ2, 272, 24);

  FSlabel42champ3 = gtk_label_new ("");
  gtk_widget_show (FSlabel42champ3);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel42champ3, 432, 104);
  gtk_widget_set_size_request (FSlabel42champ3, 256, 24);

  FSlabel43champ4 = gtk_label_new ("");
  gtk_widget_show (FSlabel43champ4);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel43champ4, 416, 144);
  gtk_widget_set_size_request (FSlabel43champ4, 264, 24);

  FSlabel44champ5 = gtk_label_new ("");
  gtk_widget_show (FSlabel44champ5);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel44champ5, 416, 256);
  gtk_widget_set_size_request (FSlabel44champ5, 256, 24);

  FSlabel45champ6 = gtk_label_new ("");
  gtk_widget_show (FSlabel45champ6);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel45champ6, 424, 296);
  gtk_widget_set_size_request (FSlabel45champ6, 240, 24);

  FSlabel47champ8 = gtk_label_new ("");
  gtk_widget_show (FSlabel47champ8);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel47champ8, 432, 376);
  gtk_widget_set_size_request (FSlabel47champ8, 240, 32);

  FSlabel48champ9 = gtk_label_new ("");
  gtk_widget_show (FSlabel48champ9);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel48champ9, 408, 416);
  gtk_widget_set_size_request (FSlabel48champ9, 232, 24);

  FSlabel46champ7 = gtk_label_new ("");
  gtk_widget_show (FSlabel46champ7);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel46champ7, 432, 336);
  gtk_widget_set_size_request (FSlabel46champ7, 232, 24);

  FSlabel50champ11 = gtk_label_new ("");
  gtk_widget_show (FSlabel50champ11);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel50champ11, 416, 536);
  gtk_widget_set_size_request (FSlabel50champ11, 232, 24);

  FSlabel49champ10 = gtk_label_new ("");
  gtk_widget_show (FSlabel49champ10);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel49champ10, 416, 456);
  gtk_widget_set_size_request (FSlabel49champ10, 256, 24);

  FSlabel51champchambre = gtk_label_new ("");
  gtk_widget_show (FSlabel51champchambre);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel51champchambre, 416, 496);
  gtk_widget_set_size_request (FSlabel51champchambre, 256, 24);

  FSlabel1msgajout = gtk_label_new ("");
  gtk_widget_show (FSlabel1msgajout);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel1msgajout, 552, 568);
  gtk_widget_set_size_request (FSlabel1msgajout, 360, 48);

  FSlabel40champ1 = gtk_label_new ("");
  gtk_widget_show (FSlabel40champ1);
  gtk_fixed_put (GTK_FIXED (fixed4), FSlabel40champ1, 440, 24);
  gtk_widget_set_size_request (FSlabel40champ1, 240, 24);

  FScombobox1chambreajout = gtk_combo_box_new_text ();
  gtk_widget_show (FScombobox1chambreajout);
  gtk_fixed_put (GTK_FIXED (fixed4), FScombobox1chambreajout, 232, 496);
  gtk_widget_set_size_request (FScombobox1chambreajout, 152, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox1chambreajout), _("Individuelle"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox1chambreajout), _("Double"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox1chambreajout), _("Triple"));

  g_signal_connect ((gpointer) FSradiobutton2homme, "toggled",
                    G_CALLBACK (on_FSradiobutton2homme_toggled),
                    NULL);
  g_signal_connect ((gpointer) FSradiobutton1femme, "toggled",
                    G_CALLBACK (on_FSradiobutton1femme_toggled),
                    NULL);
  g_signal_connect ((gpointer) FScheckbutton1condition, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) FSbutton3ajouter, "clicked",
                    G_CALLBACK (on_flisssafabutton3ajouter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (safaflissAjout, safaflissAjout, "safaflissAjout");
  GLADE_HOOKUP_OBJECT (safaflissAjout, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSentry2nom, "FSentry2nom");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSentry3prenom, "FSentry3prenom");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSentry4cin, "FSentry4cin");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSspinbutton1jour, "FSspinbutton1jour");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSspinbutton2mois, "FSspinbutton2mois");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSspinbutton3ans, "FSspinbutton3ans");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSentry5ville, "FSentry5ville");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSentry6tel, "FSentry6tel");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSentry7contact, "FSentry7contact");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSentry8nchambre, "FSentry8nchambre");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSentry9sante, "FSentry9sante");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel9nom, "FSlabel9nom");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel10prenom, "FSlabel10prenom");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel11cin, "FSlabel11cin");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel12dn, "FSlabel12dn");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel16ville, "FSlabel16ville");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel17tel, "FSlabel17tel");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel18contact, "FSlabel18contact");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel21sante, "FSlabel21sante");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel15niveau, "FSlabel15niveau");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel22payer, "FSlabel22payer");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel20nchambre, "FSlabel20nchambre");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel19chambre, "FSlabel19chambre");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSradiobutton2homme, "FSradiobutton2homme");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSradiobutton1femme, "FSradiobutton1femme");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel1idajout, "FSlabel1idajout");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSentry1idajout, "FSentry1idajout");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FScheckbutton1condition, "FScheckbutton1condition");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSbutton3ajouter, "FSbutton3ajouter");
  GLADE_HOOKUP_OBJECT (safaflissAjout, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (safaflissAjout, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (safaflissAjout, image2, "image2");
  GLADE_HOOKUP_OBJECT (safaflissAjout, label2, "label2");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FScombobox3niveau, "FScombobox3niveau");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FScombobox2payer, "FScombobox2payer");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel41champ2, "FSlabel41champ2");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel42champ3, "FSlabel42champ3");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel43champ4, "FSlabel43champ4");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel44champ5, "FSlabel44champ5");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel45champ6, "FSlabel45champ6");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel47champ8, "FSlabel47champ8");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel48champ9, "FSlabel48champ9");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel46champ7, "FSlabel46champ7");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel50champ11, "FSlabel50champ11");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel49champ10, "FSlabel49champ10");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel51champchambre, "FSlabel51champchambre");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel1msgajout, "FSlabel1msgajout");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FSlabel40champ1, "FSlabel40champ1");
  GLADE_HOOKUP_OBJECT (safaflissAjout, FScombobox1chambreajout, "FScombobox1chambreajout");

  return safaflissAjout;
}

GtkWidget*
create_safaflissModifier (void)
{
  GtkWidget *safaflissModifier;
  GtkWidget *fixed5;
  GtkWidget *FSentry10nom;
  GtkWidget *FSentry11prenom;
  GtkWidget *FSentry12cin;
  GtkObject *FSspinbutton4jour_adj;
  GtkWidget *FSspinbutton4jour;
  GtkObject *FSspinbutton5mois_adj;
  GtkWidget *FSspinbutton5mois;
  GtkObject *FSspinbutton6ans_adj;
  GtkWidget *FSspinbutton6ans;
  GtkWidget *FSentry19ville;
  GtkWidget *FSentry20tel;
  GtkWidget *FSentry21contact;
  GtkWidget *FSentry22sante;
  GtkWidget *FSentry36nchambre;
  GtkWidget *FSlabel24prenom;
  GtkWidget *FSlabel25cin;
  GtkWidget *FSlabel26dn;
  GtkWidget *FSlabel35ville;
  GtkWidget *FSlabel36tel;
  GtkWidget *FSlabel37contact;
  GtkWidget *FSlabel38sante;
  GtkWidget *FSlabel39niveau;
  GtkWidget *FSlabel58chambre;
  GtkWidget *FSlabel59nchambre;
  GtkWidget *FSlabel57payer;
  GtkWidget *FSbutton4enregistrer;
  GtkWidget *FSradiobutton4homme;
  GSList *FSradiobutton4homme_group = NULL;
  GtkWidget *FSradiobutton3femme;
  GtkWidget *FSlabel23nom;
  GtkWidget *label36;
  GtkWidget *FSentry1nonmodifiable;
  GtkWidget *FScombobox1niveaumo;
  GtkWidget *FScombobox2payermo;
  GtkWidget *FScombobox1chambremodifier;

  safaflissModifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (safaflissModifier), _("SF_modifier"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (safaflissModifier), fixed5);

  FSentry10nom = gtk_entry_new ();
  gtk_widget_show (FSentry10nom);
  gtk_fixed_put (GTK_FIXED (fixed5), FSentry10nom, 232, 64);
  gtk_widget_set_size_request (FSentry10nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry10nom), 8226);

  FSentry11prenom = gtk_entry_new ();
  gtk_widget_show (FSentry11prenom);
  gtk_fixed_put (GTK_FIXED (fixed5), FSentry11prenom, 232, 104);
  gtk_widget_set_size_request (FSentry11prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry11prenom), 8226);

  FSentry12cin = gtk_entry_new ();
  gtk_widget_show (FSentry12cin);
  gtk_fixed_put (GTK_FIXED (fixed5), FSentry12cin, 232, 144);
  gtk_widget_set_size_request (FSentry12cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry12cin), 8226);

  FSspinbutton4jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  FSspinbutton4jour = gtk_spin_button_new (GTK_ADJUSTMENT (FSspinbutton4jour_adj), 1, 0);
  gtk_widget_show (FSspinbutton4jour);
  gtk_fixed_put (GTK_FIXED (fixed5), FSspinbutton4jour, 232, 184);
  gtk_widget_set_size_request (FSspinbutton4jour, 56, 24);

  FSspinbutton5mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  FSspinbutton5mois = gtk_spin_button_new (GTK_ADJUSTMENT (FSspinbutton5mois_adj), 1, 0);
  gtk_widget_show (FSspinbutton5mois);
  gtk_fixed_put (GTK_FIXED (fixed5), FSspinbutton5mois, 320, 184);
  gtk_widget_set_size_request (FSspinbutton5mois, 56, 24);

  FSspinbutton6ans_adj = gtk_adjustment_new (1, 1990, 2030, 1, 10, 10);
  FSspinbutton6ans = gtk_spin_button_new (GTK_ADJUSTMENT (FSspinbutton6ans_adj), 1, 0);
  gtk_widget_show (FSspinbutton6ans);
  gtk_fixed_put (GTK_FIXED (fixed5), FSspinbutton6ans, 424, 184);
  gtk_widget_set_size_request (FSspinbutton6ans, 80, 24);

  FSentry19ville = gtk_entry_new ();
  gtk_widget_show (FSentry19ville);
  gtk_fixed_put (GTK_FIXED (fixed5), FSentry19ville, 232, 256);
  gtk_widget_set_size_request (FSentry19ville, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry19ville), 8226);

  FSentry20tel = gtk_entry_new ();
  gtk_widget_show (FSentry20tel);
  gtk_fixed_put (GTK_FIXED (fixed5), FSentry20tel, 232, 296);
  gtk_widget_set_size_request (FSentry20tel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry20tel), 8226);

  FSentry21contact = gtk_entry_new ();
  gtk_widget_show (FSentry21contact);
  gtk_fixed_put (GTK_FIXED (fixed5), FSentry21contact, 232, 336);
  gtk_widget_set_size_request (FSentry21contact, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry21contact), 8226);

  FSentry22sante = gtk_entry_new ();
  gtk_widget_show (FSentry22sante);
  gtk_fixed_put (GTK_FIXED (fixed5), FSentry22sante, 232, 376);
  gtk_widget_set_size_request (FSentry22sante, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry22sante), 8226);

  FSentry36nchambre = gtk_entry_new ();
  gtk_widget_show (FSentry36nchambre);
  gtk_fixed_put (GTK_FIXED (fixed5), FSentry36nchambre, 232, 536);
  gtk_widget_set_size_request (FSentry36nchambre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry36nchambre), 8226);

  FSlabel24prenom = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (FSlabel24prenom);
  gtk_fixed_put (GTK_FIXED (fixed5), FSlabel24prenom, 80, 104);
  gtk_widget_set_size_request (FSlabel24prenom, 96, 32);

  FSlabel25cin = gtk_label_new (_("CIN"));
  gtk_widget_show (FSlabel25cin);
  gtk_fixed_put (GTK_FIXED (fixed5), FSlabel25cin, 88, 144);
  gtk_widget_set_size_request (FSlabel25cin, 72, 32);

  FSlabel26dn = gtk_label_new (_("Date de Naissance"));
  gtk_widget_show (FSlabel26dn);
  gtk_fixed_put (GTK_FIXED (fixed5), FSlabel26dn, 72, 176);
  gtk_widget_set_size_request (FSlabel26dn, 144, 40);

  FSlabel35ville = gtk_label_new (_("Ville d'Origine"));
  gtk_widget_show (FSlabel35ville);
  gtk_fixed_put (GTK_FIXED (fixed5), FSlabel35ville, 80, 256);
  gtk_widget_set_size_request (FSlabel35ville, 120, 32);

  FSlabel36tel = gtk_label_new (_("N\302\260de T\303\251l\303\251phone"));
  gtk_widget_show (FSlabel36tel);
  gtk_fixed_put (GTK_FIXED (fixed5), FSlabel36tel, 80, 296);
  gtk_widget_set_size_request (FSlabel36tel, 128, 32);

  FSlabel37contact = gtk_label_new (_("Contact Parents"));
  gtk_widget_show (FSlabel37contact);
  gtk_fixed_put (GTK_FIXED (fixed5), FSlabel37contact, 72, 336);
  gtk_widget_set_size_request (FSlabel37contact, 152, 32);

  FSlabel38sante = gtk_label_new (_("Condition Sanitaire"));
  gtk_widget_show (FSlabel38sante);
  gtk_fixed_put (GTK_FIXED (fixed5), FSlabel38sante, 80, 376);
  gtk_widget_set_size_request (FSlabel38sante, 160, 32);

  FSlabel39niveau = gtk_label_new (_("Niveau"));
  gtk_widget_show (FSlabel39niveau);
  gtk_fixed_put (GTK_FIXED (fixed5), FSlabel39niveau, 88, 416);
  gtk_widget_set_size_request (FSlabel39niveau, 88, 24);

  FSlabel58chambre = gtk_label_new (_("Chambre"));
  gtk_widget_show (FSlabel58chambre);
  gtk_fixed_put (GTK_FIXED (fixed5), FSlabel58chambre, 96, 496);
  gtk_widget_set_size_request (FSlabel58chambre, 80, 24);

  FSlabel59nchambre = gtk_label_new (_("N\302\260Chambre"));
  gtk_widget_show (FSlabel59nchambre);
  gtk_fixed_put (GTK_FIXED (fixed5), FSlabel59nchambre, 88, 536);
  gtk_widget_set_size_request (FSlabel59nchambre, 112, 24);

  FSlabel57payer = gtk_label_new (_("Payement"));
  gtk_widget_show (FSlabel57payer);
  gtk_fixed_put (GTK_FIXED (fixed5), FSlabel57payer, 80, 448);
  gtk_widget_set_size_request (FSlabel57payer, 120, 40);

  FSbutton4enregistrer = gtk_button_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (FSbutton4enregistrer);
  gtk_fixed_put (GTK_FIXED (fixed5), FSbutton4enregistrer, 512, 272);
  gtk_widget_set_size_request (FSbutton4enregistrer, 120, 48);

  FSradiobutton4homme = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (FSradiobutton4homme);
  gtk_fixed_put (GTK_FIXED (fixed5), FSradiobutton4homme, 416, 224);
  gtk_widget_set_size_request (FSradiobutton4homme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (FSradiobutton4homme), FSradiobutton4homme_group);
  FSradiobutton4homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (FSradiobutton4homme));

  FSradiobutton3femme = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (FSradiobutton3femme);
  gtk_fixed_put (GTK_FIXED (fixed5), FSradiobutton3femme, 240, 224);
  gtk_widget_set_size_request (FSradiobutton3femme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (FSradiobutton3femme), FSradiobutton4homme_group);
  FSradiobutton4homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (FSradiobutton3femme));

  FSlabel23nom = gtk_label_new (_("Nom"));
  gtk_widget_show (FSlabel23nom);
  gtk_fixed_put (GTK_FIXED (fixed5), FSlabel23nom, 80, 64);
  gtk_widget_set_size_request (FSlabel23nom, 96, 32);

  label36 = gtk_label_new (_("Id"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed5), label36, 104, 24);
  gtk_widget_set_size_request (label36, 49, 17);

  FSentry1nonmodifiable = gtk_entry_new ();
  gtk_widget_show (FSentry1nonmodifiable);
  gtk_fixed_put (GTK_FIXED (fixed5), FSentry1nonmodifiable, 232, 16);
  gtk_widget_set_size_request (FSentry1nonmodifiable, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (FSentry1nonmodifiable), FALSE);
  gtk_entry_set_has_frame (GTK_ENTRY (FSentry1nonmodifiable), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry1nonmodifiable), 8226);

  FScombobox1niveaumo = gtk_combo_box_new_text ();
  gtk_widget_show (FScombobox1niveaumo);
  gtk_fixed_put (GTK_FIXED (fixed5), FScombobox1niveaumo, 232, 416);
  gtk_widget_set_size_request (FScombobox1niveaumo, 153, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox1niveaumo), _("1ere"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox1niveaumo), _("2eme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox1niveaumo), _("3eme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox1niveaumo), _("4eme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox1niveaumo), _("5eme"));

  FScombobox2payermo = gtk_combo_box_new_text ();
  gtk_widget_show (FScombobox2payermo);
  gtk_fixed_put (GTK_FIXED (fixed5), FScombobox2payermo, 231, 453);
  gtk_widget_set_size_request (FScombobox2payermo, 153, 35);
  gtk_container_set_border_width (GTK_CONTAINER (FScombobox2payermo), 33);
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox2payermo), _("par*tranche"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox2payermo), _("par*mois"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox2payermo), _("par*annee"));

  FScombobox1chambremodifier = gtk_combo_box_new_text ();
  gtk_widget_show (FScombobox1chambremodifier);
  gtk_fixed_put (GTK_FIXED (fixed5), FScombobox1chambremodifier, 232, 496);
  gtk_widget_set_size_request (FScombobox1chambremodifier, 153, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox1chambremodifier), _("Individuelle"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox1chambremodifier), _("Double"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (FScombobox1chambremodifier), _("Triple"));

  g_signal_connect ((gpointer) safaflissModifier, "focus_in_event",
                    G_CALLBACK (on_safaflissModifier_focus_in_event),
                    NULL);
  g_signal_connect ((gpointer) safaflissModifier, "destroy",
                    G_CALLBACK (on_safaflissModifier_destroy),
                    NULL);
  g_signal_connect ((gpointer) FSbutton4enregistrer, "clicked",
                    G_CALLBACK (on_FSbutton4enregistrer_clicked),
                    NULL);
  g_signal_connect ((gpointer) FSradiobutton4homme, "toggled",
                    G_CALLBACK (on_FSradiobutton4homme_toggled),
                    NULL);
  g_signal_connect ((gpointer) FSradiobutton3femme, "toggled",
                    G_CALLBACK (on_FSradiobutton3femme_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (safaflissModifier, safaflissModifier, "safaflissModifier");
  GLADE_HOOKUP_OBJECT (safaflissModifier, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSentry10nom, "FSentry10nom");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSentry11prenom, "FSentry11prenom");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSentry12cin, "FSentry12cin");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSspinbutton4jour, "FSspinbutton4jour");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSspinbutton5mois, "FSspinbutton5mois");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSspinbutton6ans, "FSspinbutton6ans");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSentry19ville, "FSentry19ville");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSentry20tel, "FSentry20tel");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSentry21contact, "FSentry21contact");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSentry22sante, "FSentry22sante");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSentry36nchambre, "FSentry36nchambre");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSlabel24prenom, "FSlabel24prenom");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSlabel25cin, "FSlabel25cin");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSlabel26dn, "FSlabel26dn");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSlabel35ville, "FSlabel35ville");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSlabel36tel, "FSlabel36tel");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSlabel37contact, "FSlabel37contact");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSlabel38sante, "FSlabel38sante");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSlabel39niveau, "FSlabel39niveau");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSlabel58chambre, "FSlabel58chambre");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSlabel59nchambre, "FSlabel59nchambre");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSlabel57payer, "FSlabel57payer");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSbutton4enregistrer, "FSbutton4enregistrer");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSradiobutton4homme, "FSradiobutton4homme");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSradiobutton3femme, "FSradiobutton3femme");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSlabel23nom, "FSlabel23nom");
  GLADE_HOOKUP_OBJECT (safaflissModifier, label36, "label36");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FSentry1nonmodifiable, "FSentry1nonmodifiable");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FScombobox1niveaumo, "FScombobox1niveaumo");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FScombobox2payermo, "FScombobox2payermo");
  GLADE_HOOKUP_OBJECT (safaflissModifier, FScombobox1chambremodifier, "FScombobox1chambremodifier");

  return safaflissModifier;
}

GtkWidget*
create_safaflissaffichage (void)
{
  GtkWidget *safaflissaffichage;
  GtkWidget *fixed11;
  GtkWidget *FSbutton7modifier;
  GtkWidget *alignment6;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *label19;
  GtkWidget *label21;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *vseparator2;
  GtkWidget *label30;
  GtkWidget *label29;
  GtkWidget *label28;
  GtkWidget *label27;
  GtkWidget *label7;
  GtkWidget *label9;
  GtkWidget *label11;
  GtkWidget *label13;
  GtkWidget *label15;
  GtkWidget *label17;
  GtkWidget *FSlabel8id22;
  GtkWidget *FSlabel10nom22;
  GtkWidget *FSlabel14cin22;
  GtkWidget *FSlabel12prenom22;
  GtkWidget *FSlabel18mois22;
  GtkWidget *FSlabel16jour22;
  GtkWidget *FSlabel20annee22;
  GtkWidget *FSlabel22sexe22;
  GtkWidget *FSlabel31ville22;
  GtkWidget *FSlabel32tel22;
  GtkWidget *FSlabel33contact22;
  GtkWidget *FSlabel34sante22;
  GtkWidget *FSlabel35niveau22;
  GtkWidget *FSlabel36payer22;
  GtkWidget *FSlabel37ch22;
  GtkWidget *FSlabel38numch22;
  GtkWidget *FSbutton8supprimer;
  GtkWidget *alignment7;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label6;
  GtkWidget *FSlabel4texte;
  GtkWidget *FSbutton1retourner;
  GtkWidget *alignment14;
  GtkWidget *hbox13;
  GtkWidget *image15;
  GtkWidget *label39;

  safaflissaffichage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (safaflissaffichage), _("SF_affichage"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (safaflissaffichage), fixed11);

  FSbutton7modifier = gtk_button_new ();
  gtk_widget_show (FSbutton7modifier);
  gtk_fixed_put (GTK_FIXED (fixed11), FSbutton7modifier, 88, 384);
  gtk_widget_set_size_request (FSbutton7modifier, 104, 48);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (FSbutton7modifier), alignment6);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  label19 = gtk_label_new (_("<span><b>Ann\303\251e :</b></span>"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed11), label19, 40, 296);
  gtk_widget_set_size_request (label19, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  label21 = gtk_label_new (_("<span><b>Sexe :</b></span>"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed11), label21, 40, 336);
  gtk_widget_set_size_request (label21, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  label23 = gtk_label_new (_("<span><b>Ville d'origine :</b></span>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed11), label23, 272, 56);
  gtk_widget_set_size_request (label23, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  label24 = gtk_label_new (_("<span><b>N\302\260  telephone :</b></span>"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed11), label24, 272, 96);
  gtk_widget_set_size_request (label24, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  label25 = gtk_label_new (_("<span><b>Contact parent :</b></span>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed11), label25, 264, 136);
  gtk_widget_set_size_request (label25, 120, 32);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  label26 = gtk_label_new (_("<span><b>Condition Sanitaire :</b></span>"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed11), label26, 264, 176);
  gtk_widget_set_size_request (label26, 136, 32);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_fixed_put (GTK_FIXED (fixed11), vseparator2, 224, 56);
  gtk_widget_set_size_request (vseparator2, 30, 328);

  label30 = gtk_label_new (_("<span><b>N\302\260chambre :</b></span>"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed11), label30, 280, 336);
  gtk_widget_set_size_request (label30, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  label29 = gtk_label_new (_("<span><b>Chambre :</b></span>"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed11), label29, 280, 296);
  gtk_widget_set_size_request (label29, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  label28 = gtk_label_new (_("<span><b>Payement :</b></span>"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed11), label28, 280, 256);
  gtk_widget_set_size_request (label28, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  label27 = gtk_label_new (_("<span><b>Niveau :</b></span>"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed11), label27, 280, 216);
  gtk_widget_set_size_request (label27, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  label7 = gtk_label_new (_("<span><b>identifiant :</b></span>"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed11), label7, 40, 56);
  gtk_widget_set_size_request (label7, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  label9 = gtk_label_new (_("<span><b>Nom :</b></span>"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed11), label9, 40, 96);
  gtk_widget_set_size_request (label9, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  label11 = gtk_label_new (_("<span><b>Pr\303\251nom :</b></span>"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed11), label11, 40, 136);
  gtk_widget_set_size_request (label11, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  label13 = gtk_label_new (_("<span><b>CIN :</b></span>"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed11), label13, 40, 176);
  gtk_widget_set_size_request (label13, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  label15 = gtk_label_new (_("<span><b>date de naissance :\n\t\t       Jour :</b></span>"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed11), label15, 0, 195);
  gtk_widget_set_size_request (label15, 144, 56);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  label17 = gtk_label_new (_("<span><b>Mois :</b></span>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed11), label17, 40, 256);
  gtk_widget_set_size_request (label17, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  FSlabel8id22 = gtk_label_new ("");
  gtk_widget_show (FSlabel8id22);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel8id22, 136, 56);
  gtk_widget_set_size_request (FSlabel8id22, 104, 32);

  FSlabel10nom22 = gtk_label_new ("");
  gtk_widget_show (FSlabel10nom22);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel10nom22, 136, 96);
  gtk_widget_set_size_request (FSlabel10nom22, 104, 32);

  FSlabel14cin22 = gtk_label_new ("");
  gtk_widget_show (FSlabel14cin22);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel14cin22, 136, 176);
  gtk_widget_set_size_request (FSlabel14cin22, 104, 32);

  FSlabel12prenom22 = gtk_label_new ("");
  gtk_widget_show (FSlabel12prenom22);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel12prenom22, 136, 136);
  gtk_widget_set_size_request (FSlabel12prenom22, 104, 32);

  FSlabel18mois22 = gtk_label_new ("");
  gtk_widget_show (FSlabel18mois22);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel18mois22, 136, 256);
  gtk_widget_set_size_request (FSlabel18mois22, 104, 32);

  FSlabel16jour22 = gtk_label_new ("");
  gtk_widget_show (FSlabel16jour22);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel16jour22, 144, 216);
  gtk_widget_set_size_request (FSlabel16jour22, 104, 32);

  FSlabel20annee22 = gtk_label_new ("");
  gtk_widget_show (FSlabel20annee22);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel20annee22, 136, 296);
  gtk_widget_set_size_request (FSlabel20annee22, 104, 32);

  FSlabel22sexe22 = gtk_label_new ("");
  gtk_widget_show (FSlabel22sexe22);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel22sexe22, 136, 336);
  gtk_widget_set_size_request (FSlabel22sexe22, 104, 32);

  FSlabel31ville22 = gtk_label_new ("");
  gtk_widget_show (FSlabel31ville22);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel31ville22, 392, 56);
  gtk_widget_set_size_request (FSlabel31ville22, 104, 32);

  FSlabel32tel22 = gtk_label_new ("");
  gtk_widget_show (FSlabel32tel22);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel32tel22, 392, 96);
  gtk_widget_set_size_request (FSlabel32tel22, 104, 32);

  FSlabel33contact22 = gtk_label_new ("");
  gtk_widget_show (FSlabel33contact22);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel33contact22, 392, 136);
  gtk_widget_set_size_request (FSlabel33contact22, 104, 32);

  FSlabel34sante22 = gtk_label_new ("");
  gtk_widget_show (FSlabel34sante22);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel34sante22, 400, 176);
  gtk_widget_set_size_request (FSlabel34sante22, 104, 32);

  FSlabel35niveau22 = gtk_label_new ("");
  gtk_widget_show (FSlabel35niveau22);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel35niveau22, 392, 216);
  gtk_widget_set_size_request (FSlabel35niveau22, 104, 32);

  FSlabel36payer22 = gtk_label_new ("");
  gtk_widget_show (FSlabel36payer22);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel36payer22, 392, 256);
  gtk_widget_set_size_request (FSlabel36payer22, 104, 32);

  FSlabel37ch22 = gtk_label_new ("");
  gtk_widget_show (FSlabel37ch22);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel37ch22, 392, 296);
  gtk_widget_set_size_request (FSlabel37ch22, 104, 32);

  FSlabel38numch22 = gtk_label_new ("");
  gtk_widget_show (FSlabel38numch22);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel38numch22, 392, 336);
  gtk_widget_set_size_request (FSlabel38numch22, 104, 32);

  FSbutton8supprimer = gtk_button_new ();
  gtk_widget_show (FSbutton8supprimer);
  gtk_fixed_put (GTK_FIXED (fixed11), FSbutton8supprimer, 296, 384);
  gtk_widget_set_size_request (FSbutton8supprimer, 104, 48);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (FSbutton8supprimer), alignment7);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox6), label6, FALSE, FALSE, 0);

  FSlabel4texte = gtk_label_new (_("<span color=\"#006080\" font_desc='Tahoma 12'><b>Liste des Donn\303\251es de l'\303\251tudiant</b></span>"));
  gtk_widget_show (FSlabel4texte);
  gtk_fixed_put (GTK_FIXED (fixed11), FSlabel4texte, 64, 0);
  gtk_widget_set_size_request (FSlabel4texte, 400, 56);
  gtk_label_set_use_markup (GTK_LABEL (FSlabel4texte), TRUE);

  FSbutton1retourner = gtk_button_new ();
  gtk_widget_show (FSbutton1retourner);
  gtk_fixed_put (GTK_FIXED (fixed11), FSbutton1retourner, 16, 16);
  gtk_widget_set_size_request (FSbutton1retourner, 80, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (FSbutton1retourner), alignment14);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox13);

  image15 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox13), image15, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox13), label39, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) safaflissaffichage, "focus_in_event",
                    G_CALLBACK (on_safaflissaffichage_focus_in_event),
                    NULL);
  g_signal_connect ((gpointer) FSbutton7modifier, "clicked",
                    G_CALLBACK (on_FSbutton7modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) FSbutton8supprimer, "clicked",
                    G_CALLBACK (on_FSbutton8supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) FSbutton1retourner, "clicked",
                    G_CALLBACK (on_FSbutton1retourner_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (safaflissaffichage, safaflissaffichage, "safaflissaffichage");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSbutton7modifier, "FSbutton7modifier");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, image5, "image5");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label5, "label5");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label19, "label19");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label21, "label21");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label23, "label23");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label24, "label24");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label25, "label25");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label26, "label26");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label30, "label30");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label29, "label29");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label28, "label28");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label27, "label27");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label7, "label7");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label9, "label9");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label11, "label11");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label13, "label13");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label15, "label15");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label17, "label17");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel8id22, "FSlabel8id22");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel10nom22, "FSlabel10nom22");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel14cin22, "FSlabel14cin22");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel12prenom22, "FSlabel12prenom22");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel18mois22, "FSlabel18mois22");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel16jour22, "FSlabel16jour22");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel20annee22, "FSlabel20annee22");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel22sexe22, "FSlabel22sexe22");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel31ville22, "FSlabel31ville22");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel32tel22, "FSlabel32tel22");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel33contact22, "FSlabel33contact22");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel34sante22, "FSlabel34sante22");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel35niveau22, "FSlabel35niveau22");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel36payer22, "FSlabel36payer22");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel37ch22, "FSlabel37ch22");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel38numch22, "FSlabel38numch22");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSbutton8supprimer, "FSbutton8supprimer");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, image6, "image6");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label6, "label6");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSlabel4texte, "FSlabel4texte");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, FSbutton1retourner, "FSbutton1retourner");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, image15, "image15");
  GLADE_HOOKUP_OBJECT (safaflissaffichage, label39, "label39");

  return safaflissaffichage;
}

GtkWidget*
create_safaflissstatistique (void)
{
  GtkWidget *safaflissstatistique;
  GtkWidget *fixed12;
  GtkWidget *FSentry1stat9;
  GtkWidget *FSlabel33nbetud9;
  GtkWidget *FSbutton2okii9;
  GtkWidget *image10;
  GtkWidget *FSlabel34nbetud9;
  GtkWidget *vseparator3;
  GtkWidget *FSlabel1ereannee;
  GtkWidget *FSlabel382eme;
  GtkWidget *FSlabel404eme;
  GtkWidget *FSlabel445eme;
  GtkWidget *FSlabel371erestat;
  GtkWidget *FSlabel412emestat;
  GtkWidget *FSlabel423emestat;
  GtkWidget *FSlabel434emestat;
  GtkWidget *FSlabel393eme;
  GtkWidget *FSlabel455emestat;
  GtkWidget *FSlabel62nbre;
  GtkWidget *FSlabel35stat9;

  safaflissstatistique = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (safaflissstatistique), _("SF_statistique"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (safaflissstatistique), fixed12);

  FSentry1stat9 = gtk_entry_new ();
  gtk_widget_show (FSentry1stat9);
  gtk_fixed_put (GTK_FIXED (fixed12), FSentry1stat9, 136, 152);
  gtk_widget_set_size_request (FSentry1stat9, 104, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry1stat9), 8226);

  FSlabel33nbetud9 = gtk_label_new (_("Le nombre d'etudiants :"));
  gtk_widget_show (FSlabel33nbetud9);
  gtk_fixed_put (GTK_FIXED (fixed12), FSlabel33nbetud9, 0, 208);
  gtk_widget_set_size_request (FSlabel33nbetud9, 184, 40);

  FSbutton2okii9 = gtk_button_new ();
  gtk_widget_show (FSbutton2okii9);
  gtk_fixed_put (GTK_FIXED (fixed12), FSbutton2okii9, 240, 152);
  gtk_widget_set_size_request (FSbutton2okii9, 40, 32);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_container_add (GTK_CONTAINER (FSbutton2okii9), image10);

  FSlabel34nbetud9 = gtk_label_new ("");
  gtk_widget_show (FSlabel34nbetud9);
  gtk_fixed_put (GTK_FIXED (fixed12), FSlabel34nbetud9, 168, 256);
  gtk_widget_set_size_request (FSlabel34nbetud9, 64, 40);

  vseparator3 = gtk_vseparator_new ();
  gtk_widget_show (vseparator3);
  gtk_fixed_put (GTK_FIXED (fixed12), vseparator3, 280, 144);
  gtk_widget_set_size_request (vseparator3, 16, 208);

  FSlabel1ereannee = gtk_label_new (_("1\303\250re ann\303\251e"));
  gtk_widget_show (FSlabel1ereannee);
  gtk_fixed_put (GTK_FIXED (fixed12), FSlabel1ereannee, 312, 152);
  gtk_widget_set_size_request (FSlabel1ereannee, 96, 24);

  FSlabel382eme = gtk_label_new (_("2\303\250me ann\303\251e"));
  gtk_widget_show (FSlabel382eme);
  gtk_fixed_put (GTK_FIXED (fixed12), FSlabel382eme, 312, 192);
  gtk_widget_set_size_request (FSlabel382eme, 104, 24);

  FSlabel404eme = gtk_label_new (_("4\303\250me ann\303\251e"));
  gtk_widget_show (FSlabel404eme);
  gtk_fixed_put (GTK_FIXED (fixed12), FSlabel404eme, 320, 272);
  gtk_widget_set_size_request (FSlabel404eme, 96, 24);

  FSlabel445eme = gtk_label_new (_("5\303\250me ann\303\251e"));
  gtk_widget_show (FSlabel445eme);
  gtk_fixed_put (GTK_FIXED (fixed12), FSlabel445eme, 320, 312);
  gtk_widget_set_size_request (FSlabel445eme, 96, 24);

  FSlabel371erestat = gtk_label_new ("");
  gtk_widget_show (FSlabel371erestat);
  gtk_fixed_put (GTK_FIXED (fixed12), FSlabel371erestat, 448, 152);
  gtk_widget_set_size_request (FSlabel371erestat, 49, 17);

  FSlabel412emestat = gtk_label_new ("");
  gtk_widget_show (FSlabel412emestat);
  gtk_fixed_put (GTK_FIXED (fixed12), FSlabel412emestat, 448, 192);
  gtk_widget_set_size_request (FSlabel412emestat, 49, 17);

  FSlabel423emestat = gtk_label_new ("");
  gtk_widget_show (FSlabel423emestat);
  gtk_fixed_put (GTK_FIXED (fixed12), FSlabel423emestat, 448, 232);
  gtk_widget_set_size_request (FSlabel423emestat, 49, 17);

  FSlabel434emestat = gtk_label_new ("");
  gtk_widget_show (FSlabel434emestat);
  gtk_fixed_put (GTK_FIXED (fixed12), FSlabel434emestat, 448, 272);
  gtk_widget_set_size_request (FSlabel434emestat, 49, 17);

  FSlabel393eme = gtk_label_new (_("3\303\250me ann\303\251e"));
  gtk_widget_show (FSlabel393eme);
  gtk_fixed_put (GTK_FIXED (fixed12), FSlabel393eme, 312, 232);
  gtk_widget_set_size_request (FSlabel393eme, 104, 24);

  FSlabel455emestat = gtk_label_new ("");
  gtk_widget_show (FSlabel455emestat);
  gtk_fixed_put (GTK_FIXED (fixed12), FSlabel455emestat, 448, 312);
  gtk_widget_set_size_request (FSlabel455emestat, 49, 17);

  FSlabel62nbre = gtk_label_new (_("<span color=\"#006080\" font_desc='Tahoma 12'><b>Le nombre des \303\251tudiants par niveau</b></span>"));
  gtk_widget_show (FSlabel62nbre);
  gtk_fixed_put (GTK_FIXED (fixed12), FSlabel62nbre, 96, 24);
  gtk_widget_set_size_request (FSlabel62nbre, 352, 64);
  gtk_label_set_use_markup (GTK_LABEL (FSlabel62nbre), TRUE);

  FSlabel35stat9 = gtk_label_new (_("Entrer le niveau :"));
  gtk_widget_show (FSlabel35stat9);
  gtk_fixed_put (GTK_FIXED (fixed12), FSlabel35stat9, 0, 152);
  gtk_widget_set_size_request (FSlabel35stat9, 144, 32);

  g_signal_connect ((gpointer) safaflissstatistique, "focus_in_event",
                    G_CALLBACK (on_safaflissstatistique_focus_in_event),
                    NULL);
  g_signal_connect ((gpointer) FSbutton2okii9, "clicked",
                    G_CALLBACK (on_FSbutton2okii9_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (safaflissstatistique, safaflissstatistique, "safaflissstatistique");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, FSentry1stat9, "FSentry1stat9");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, FSlabel33nbetud9, "FSlabel33nbetud9");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, FSbutton2okii9, "FSbutton2okii9");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, image10, "image10");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, FSlabel34nbetud9, "FSlabel34nbetud9");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, vseparator3, "vseparator3");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, FSlabel1ereannee, "FSlabel1ereannee");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, FSlabel382eme, "FSlabel382eme");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, FSlabel404eme, "FSlabel404eme");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, FSlabel445eme, "FSlabel445eme");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, FSlabel371erestat, "FSlabel371erestat");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, FSlabel412emestat, "FSlabel412emestat");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, FSlabel423emestat, "FSlabel423emestat");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, FSlabel434emestat, "FSlabel434emestat");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, FSlabel393eme, "FSlabel393eme");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, FSlabel455emestat, "FSlabel455emestat");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, FSlabel62nbre, "FSlabel62nbre");
  GLADE_HOOKUP_OBJECT (safaflissstatistique, FSlabel35stat9, "FSlabel35stat9");

  return safaflissstatistique;
}

GtkWidget*
create_safaflissInscription (void)
{
  GtkWidget *safaflissInscription;
  GtkWidget *fixed13;
  GtkWidget *FSlabel2nom_ins;
  GtkWidget *FSlabel3prenom_ins;
  GtkWidget *FSlabel4user_ins;
  GtkWidget *FSlabel5pass_ins;
  GtkWidget *FSlabel6role_ins;
  GtkWidget *FSentry1nom_ins;
  GtkWidget *FSentry2prenom_ins;
  GtkWidget *FSentry3user_ins;
  GtkWidget *FSentry4pass_ins;
  GtkWidget *FSentry5role_ins;
  GtkWidget *FSlabel7liste_ins;
  GtkWidget *FSlabel1inscri;
  GtkWidget *FSbutton1ajout_ins;
  GtkWidget *FSimage1img;

  safaflissInscription = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (safaflissInscription), _("Inscription"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (safaflissInscription), fixed13);

  FSlabel2nom_ins = gtk_label_new (_("Nom :"));
  gtk_widget_show (FSlabel2nom_ins);
  gtk_fixed_put (GTK_FIXED (fixed13), FSlabel2nom_ins, 136, 144);
  gtk_widget_set_size_request (FSlabel2nom_ins, 80, 32);

  FSlabel3prenom_ins = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (FSlabel3prenom_ins);
  gtk_fixed_put (GTK_FIXED (fixed13), FSlabel3prenom_ins, 128, 208);
  gtk_widget_set_size_request (FSlabel3prenom_ins, 80, 32);

  FSlabel4user_ins = gtk_label_new (_("Username :"));
  gtk_widget_show (FSlabel4user_ins);
  gtk_fixed_put (GTK_FIXED (fixed13), FSlabel4user_ins, 120, 272);
  gtk_widget_set_size_request (FSlabel4user_ins, 80, 32);

  FSlabel5pass_ins = gtk_label_new (_("Password :"));
  gtk_widget_show (FSlabel5pass_ins);
  gtk_fixed_put (GTK_FIXED (fixed13), FSlabel5pass_ins, 120, 328);
  gtk_widget_set_size_request (FSlabel5pass_ins, 88, 32);

  FSlabel6role_ins = gtk_label_new (_("Role :"));
  gtk_widget_show (FSlabel6role_ins);
  gtk_fixed_put (GTK_FIXED (fixed13), FSlabel6role_ins, 136, 384);
  gtk_widget_set_size_request (FSlabel6role_ins, 64, 32);

  FSentry1nom_ins = gtk_entry_new ();
  gtk_widget_show (FSentry1nom_ins);
  gtk_fixed_put (GTK_FIXED (fixed13), FSentry1nom_ins, 280, 144);
  gtk_widget_set_size_request (FSentry1nom_ins, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry1nom_ins), 8226);

  FSentry2prenom_ins = gtk_entry_new ();
  gtk_widget_show (FSentry2prenom_ins);
  gtk_fixed_put (GTK_FIXED (fixed13), FSentry2prenom_ins, 280, 208);
  gtk_widget_set_size_request (FSentry2prenom_ins, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry2prenom_ins), 8226);

  FSentry3user_ins = gtk_entry_new ();
  gtk_widget_show (FSentry3user_ins);
  gtk_fixed_put (GTK_FIXED (fixed13), FSentry3user_ins, 280, 272);
  gtk_widget_set_size_request (FSentry3user_ins, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry3user_ins), 8226);

  FSentry4pass_ins = gtk_entry_new ();
  gtk_widget_show (FSentry4pass_ins);
  gtk_fixed_put (GTK_FIXED (fixed13), FSentry4pass_ins, 280, 328);
  gtk_widget_set_size_request (FSentry4pass_ins, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry4pass_ins), 8226);

  FSentry5role_ins = gtk_entry_new ();
  gtk_widget_show (FSentry5role_ins);
  gtk_fixed_put (GTK_FIXED (fixed13), FSentry5role_ins, 280, 384);
  gtk_widget_set_size_request (FSentry5role_ins, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry5role_ins), 8226);

  FSlabel7liste_ins = gtk_label_new (_("(1:Admin  2:Agent du Foyer  3:Technicien  4:Nutritionniste  5:Agent du retaurant  6:Etudiant)"));
  gtk_widget_show (FSlabel7liste_ins);
  gtk_fixed_put (GTK_FIXED (fixed13), FSlabel7liste_ins, 64, 440);
  gtk_widget_set_size_request (FSlabel7liste_ins, 632, 32);

  FSlabel1inscri = gtk_label_new (_("Inscription"));
  gtk_widget_show (FSlabel1inscri);
  gtk_fixed_put (GTK_FIXED (fixed13), FSlabel1inscri, 296, 64);
  gtk_widget_set_size_request (FSlabel1inscri, 120, 48);

  FSbutton1ajout_ins = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (FSbutton1ajout_ins);
  gtk_fixed_put (GTK_FIXED (fixed13), FSbutton1ajout_ins, 552, 240);
  gtk_widget_set_size_request (FSbutton1ajout_ins, 128, 48);

  FSimage1img = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (FSimage1img);
  gtk_fixed_put (GTK_FIXED (fixed13), FSimage1img, 544, 244);
  gtk_widget_set_size_request (FSimage1img, 45, 40);

  g_signal_connect ((gpointer) FSbutton1ajout_ins, "clicked",
                    G_CALLBACK (on_FSbutton1ajout_ins_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (safaflissInscription, safaflissInscription, "safaflissInscription");
  GLADE_HOOKUP_OBJECT (safaflissInscription, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (safaflissInscription, FSlabel2nom_ins, "FSlabel2nom_ins");
  GLADE_HOOKUP_OBJECT (safaflissInscription, FSlabel3prenom_ins, "FSlabel3prenom_ins");
  GLADE_HOOKUP_OBJECT (safaflissInscription, FSlabel4user_ins, "FSlabel4user_ins");
  GLADE_HOOKUP_OBJECT (safaflissInscription, FSlabel5pass_ins, "FSlabel5pass_ins");
  GLADE_HOOKUP_OBJECT (safaflissInscription, FSlabel6role_ins, "FSlabel6role_ins");
  GLADE_HOOKUP_OBJECT (safaflissInscription, FSentry1nom_ins, "FSentry1nom_ins");
  GLADE_HOOKUP_OBJECT (safaflissInscription, FSentry2prenom_ins, "FSentry2prenom_ins");
  GLADE_HOOKUP_OBJECT (safaflissInscription, FSentry3user_ins, "FSentry3user_ins");
  GLADE_HOOKUP_OBJECT (safaflissInscription, FSentry4pass_ins, "FSentry4pass_ins");
  GLADE_HOOKUP_OBJECT (safaflissInscription, FSentry5role_ins, "FSentry5role_ins");
  GLADE_HOOKUP_OBJECT (safaflissInscription, FSlabel7liste_ins, "FSlabel7liste_ins");
  GLADE_HOOKUP_OBJECT (safaflissInscription, FSlabel1inscri, "FSlabel1inscri");
  GLADE_HOOKUP_OBJECT (safaflissInscription, FSbutton1ajout_ins, "FSbutton1ajout_ins");
  GLADE_HOOKUP_OBJECT (safaflissInscription, FSimage1img, "FSimage1img");

  return safaflissInscription;
}

GtkWidget*
create_safaflissauthentification (void)
{
  GtkWidget *safaflissauthentification;
  GtkWidget *fixed14;
  GtkWidget *FSentry6user_auth;
  GtkWidget *FSentry7pass_auth;
  GtkWidget *FSlabel8user_auth;
  GtkWidget *FSlabel9pass_auth;
  GtkWidget *FSlabel1msg;
  GtkWidget *FSbutton2log_auth;
  GtkWidget *FSimage2img;

  safaflissauthentification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (safaflissauthentification), _("Authentification"));

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (safaflissauthentification), fixed14);

  FSentry6user_auth = gtk_entry_new ();
  gtk_widget_show (FSentry6user_auth);
  gtk_fixed_put (GTK_FIXED (fixed14), FSentry6user_auth, 200, 72);
  gtk_widget_set_size_request (FSentry6user_auth, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry6user_auth), 8226);

  FSentry7pass_auth = gtk_entry_new ();
  gtk_widget_show (FSentry7pass_auth);
  gtk_fixed_put (GTK_FIXED (fixed14), FSentry7pass_auth, 200, 160);
  gtk_widget_set_size_request (FSentry7pass_auth, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (FSentry7pass_auth), 8226);

  FSlabel8user_auth = gtk_label_new (_("Username"));
  gtk_widget_show (FSlabel8user_auth);
  gtk_fixed_put (GTK_FIXED (fixed14), FSlabel8user_auth, 72, 64);
  gtk_widget_set_size_request (FSlabel8user_auth, 96, 40);

  FSlabel9pass_auth = gtk_label_new (_("Password"));
  gtk_widget_show (FSlabel9pass_auth);
  gtk_fixed_put (GTK_FIXED (fixed14), FSlabel9pass_auth, 72, 152);
  gtk_widget_set_size_request (FSlabel9pass_auth, 88, 40);

  FSlabel1msg = gtk_label_new ("");
  gtk_widget_show (FSlabel1msg);
  gtk_fixed_put (GTK_FIXED (fixed14), FSlabel1msg, 168, 208);
  gtk_widget_set_size_request (FSlabel1msg, 232, 32);

  FSbutton2log_auth = gtk_button_new_with_mnemonic (_("Login"));
  gtk_widget_show (FSbutton2log_auth);
  gtk_fixed_put (GTK_FIXED (fixed14), FSbutton2log_auth, 208, 240);
  gtk_widget_set_size_request (FSbutton2log_auth, 104, 48);

  FSimage2img = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (FSimage2img);
  gtk_fixed_put (GTK_FIXED (fixed14), FSimage2img, 192, 240);
  gtk_widget_set_size_request (FSimage2img, 64, 48);

  g_signal_connect ((gpointer) FSbutton2log_auth, "clicked",
                    G_CALLBACK (on_FSbutton2log_auth_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (safaflissauthentification, safaflissauthentification, "safaflissauthentification");
  GLADE_HOOKUP_OBJECT (safaflissauthentification, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (safaflissauthentification, FSentry6user_auth, "FSentry6user_auth");
  GLADE_HOOKUP_OBJECT (safaflissauthentification, FSentry7pass_auth, "FSentry7pass_auth");
  GLADE_HOOKUP_OBJECT (safaflissauthentification, FSlabel8user_auth, "FSlabel8user_auth");
  GLADE_HOOKUP_OBJECT (safaflissauthentification, FSlabel9pass_auth, "FSlabel9pass_auth");
  GLADE_HOOKUP_OBJECT (safaflissauthentification, FSlabel1msg, "FSlabel1msg");
  GLADE_HOOKUP_OBJECT (safaflissauthentification, FSbutton2log_auth, "FSbutton2log_auth");
  GLADE_HOOKUP_OBJECT (safaflissauthentification, FSimage2img, "FSimage2img");

  return safaflissauthentification;
}

GtkWidget*
create_safaflisssure (void)
{
  GtkWidget *safaflisssure;
  GdkPixbuf *safaflisssure_icon_pixbuf;
  GtkWidget *fixed15;
  GtkWidget *FSbutton2non;
  GtkWidget *FSlabel33suppmsg;
  GtkWidget *FSbutton1oui;

  safaflisssure = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (safaflisssure), _("supprimer"));
  safaflisssure_icon_pixbuf = create_pixbuf ("Capture du 2021-10-17 10-03-41.png");
  if (safaflisssure_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (safaflisssure), safaflisssure_icon_pixbuf);
      gdk_pixbuf_unref (safaflisssure_icon_pixbuf);
    }

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (safaflisssure), fixed15);

  FSbutton2non = gtk_button_new_with_mnemonic (_("non"));
  gtk_widget_show (FSbutton2non);
  gtk_fixed_put (GTK_FIXED (fixed15), FSbutton2non, 248, 184);
  gtk_widget_set_size_request (FSbutton2non, 66, 29);

  FSlabel33suppmsg = gtk_label_new (_("Voulez-vous vraiment supprimer cet \303\251tudiant?"));
  gtk_widget_show (FSlabel33suppmsg);
  gtk_fixed_put (GTK_FIXED (fixed15), FSlabel33suppmsg, 56, 104);
  gtk_widget_set_size_request (FSlabel33suppmsg, 320, 48);

  FSbutton1oui = gtk_button_new_with_mnemonic (_("oui"));
  gtk_widget_show (FSbutton1oui);
  gtk_fixed_put (GTK_FIXED (fixed15), FSbutton1oui, 120, 184);
  gtk_widget_set_size_request (FSbutton1oui, 66, 29);

  g_signal_connect ((gpointer) safaflisssure, "focus_in_event",
                    G_CALLBACK (on_safaflisssure_focus_in_event),
                    NULL);
  g_signal_connect ((gpointer) FSbutton2non, "clicked",
                    G_CALLBACK (on_FSbutton2non_clicked),
                    NULL);
  g_signal_connect ((gpointer) FSbutton1oui, "clicked",
                    G_CALLBACK (on_FSbutton1oui_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (safaflisssure, safaflisssure, "safaflisssure");
  GLADE_HOOKUP_OBJECT (safaflisssure, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (safaflisssure, FSbutton2non, "FSbutton2non");
  GLADE_HOOKUP_OBJECT (safaflisssure, FSlabel33suppmsg, "FSlabel33suppmsg");
  GLADE_HOOKUP_OBJECT (safaflisssure, FSbutton1oui, "FSbutton1oui");

  return safaflisssure;
}

GtkWidget*
create_Flisssafawindow1modif_ajout_supp (void)
{
  GtkWidget *Flisssafawindow1modif_ajout_supp;
  GtkWidget *fixed16;
  GtkWidget *FSlabel37messagemod_aj_supp;

  Flisssafawindow1modif_ajout_supp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Flisssafawindow1modif_ajout_supp), _("modif_supp_ajout"));

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (Flisssafawindow1modif_ajout_supp), fixed16);

  FSlabel37messagemod_aj_supp = gtk_label_new ("");
  gtk_widget_show (FSlabel37messagemod_aj_supp);
  gtk_fixed_put (GTK_FIXED (fixed16), FSlabel37messagemod_aj_supp, 56, 104);
  gtk_widget_set_size_request (FSlabel37messagemod_aj_supp, 328, 48);

  g_signal_connect ((gpointer) Flisssafawindow1modif_ajout_supp, "focus_in_event",
                    G_CALLBACK (on_Flisssafawindow1modif_ajout_supp_focus_in_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Flisssafawindow1modif_ajout_supp, Flisssafawindow1modif_ajout_supp, "Flisssafawindow1modif_ajout_supp");
  GLADE_HOOKUP_OBJECT (Flisssafawindow1modif_ajout_supp, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (Flisssafawindow1modif_ajout_supp, FSlabel37messagemod_aj_supp, "FSlabel37messagemod_aj_supp");

  return Flisssafawindow1modif_ajout_supp;
}

GtkWidget*
create_safaflisswindow1ouinon (void)
{
  GtkWidget *safaflisswindow1ouinon;
  GtkWidget *fixed17;
  GtkWidget *FSlabel36ouinon;
  GtkWidget *FSbutton2window2non;
  GtkWidget *FSbutton1window2oui;

  safaflisswindow1ouinon = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (safaflisswindow1ouinon), _("safaflisswindow1ouinon"));

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (safaflisswindow1ouinon), fixed17);

  FSlabel36ouinon = gtk_label_new (_("Voulez-vous vraiment supprimer cet \303\251tudiant?"));
  gtk_widget_show (FSlabel36ouinon);
  gtk_fixed_put (GTK_FIXED (fixed17), FSlabel36ouinon, 32, 80);
  gtk_widget_set_size_request (FSlabel36ouinon, 336, 40);

  FSbutton2window2non = gtk_button_new_with_mnemonic (_("non"));
  gtk_widget_show (FSbutton2window2non);
  gtk_fixed_put (GTK_FIXED (fixed17), FSbutton2window2non, 256, 160);
  gtk_widget_set_size_request (FSbutton2window2non, 66, 29);

  FSbutton1window2oui = gtk_button_new_with_mnemonic (_("oui"));
  gtk_widget_show (FSbutton1window2oui);
  gtk_fixed_put (GTK_FIXED (fixed17), FSbutton1window2oui, 88, 160);
  gtk_widget_set_size_request (FSbutton1window2oui, 66, 29);

  g_signal_connect ((gpointer) FSbutton2window2non, "clicked",
                    G_CALLBACK (on_FSbutton2window2non_clicked),
                    NULL);
  g_signal_connect ((gpointer) FSbutton1window2oui, "clicked",
                    G_CALLBACK (on_FSbutton1window2oui_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (safaflisswindow1ouinon, safaflisswindow1ouinon, "safaflisswindow1ouinon");
  GLADE_HOOKUP_OBJECT (safaflisswindow1ouinon, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (safaflisswindow1ouinon, FSlabel36ouinon, "FSlabel36ouinon");
  GLADE_HOOKUP_OBJECT (safaflisswindow1ouinon, FSbutton2window2non, "FSbutton2window2non");
  GLADE_HOOKUP_OBJECT (safaflisswindow1ouinon, FSbutton1window2oui, "FSbutton1window2oui");

  return safaflisswindow1ouinon;
}

